### ISSUE TITLE
Connection to an LDAP server fails the first time

### ISSUE THREAD

**Issue by bjorntropf** [Planisware/plw-devenv#1]
This issue only seems to happen when connecting to an LDAP server.

On the first connection try, a username and password is asked and an error occurs afterwards.
On the second try, no username or password is asked and the connection succeeds.

> Contacting host: 10.10.212.182:80
> There was an error connecting to the Intranet server
> Contacting host: 10.10.212.182:80
> Wrote /var/folders/7k/hsbw874d7sx6jx3z93qt86rc0000gn/T/isconnect11383_Os
> Now connected to _ on port 34081

**Comment by tiboroche** [comment]
Can I have all the content of the *Messages* buffer for both connections please ?

**Comment by bjorntropf** [comment]
Unfortunately, there are no other messages there. (Except for the emacs startup stuff)
This is what I get when I use `(setq debug-on-message "There was an error.*")`

> Debugger entered--Lisp error: "There was an error connecting to the Intranet server"
>   message("There was an error connecting to the Intranet server")
>   connect-is-with-url("http://10.10.212.182/...01/OPX2/vm...:8401/home")
>   funcall-interactively(connect-is-with-url "http://10.10.212.182/...01/OPX2/vm...:8401/home")
>   call-interactively(connect-is-with-url nil nil)
>   command-execute(connect-is-with-url)

I'll see if I can add some printfs in the **connect-is-with-url** function to figure out what is going on. The second connection always succeeds.

**Comment by bjorntropf** [comment]
So I added prints directly after the let bindings for baseurl, host and data: [connect-is-with-url.txt](https://github.com/Planisware/plw-devenv/files/1040539/connect-is-with-url.txt)
This is the output for the first and the second call of the function: (removed empty lines)

```
"http://10.10.212.182/...01/OPX2/vm...:8401/"
"10.10.212.182"
Contacting host: 10.10.212.182:80
"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">"
There was an error connecting to the Intranet server

"http://10.10.212.182/...01/OPX2/vm...:8401/"
"10.10.212.182"
Contacting host: 10.10.212.182:80
"32977 0 :upper (10 (0) :FINAL 41) 1"
Wrote /var/folders/7k/hsbw874d7sx6jx3z93qt86rc0000gn/T/isconnect39399ejM
```

I can evaluate more specific prints if you send me a modified function.

**Comment by bjorntropf** [comment]
We have redefined the function with this simple workaround for quite some time.
It could end in a infinite loop, but so far that has not happened at all.

Closing this issue for now as this no longer affects us.
A proper solution is nonetheless welcome :-)
I might open a pull request for it in the future.

```
(defun connect-is-with-url (url)
  (interactive "sUrl of the Intranet server: ")
  (let* ((file (make-temp-file "isconnect"))
         (baseurl (progn (string-match *base-url-regexp* url)
                         (match-string 0 url)))
         (host (progn (string-match *host-regexp* url)
                      (match-string 1 url))))
    (cond (baseurl
           (let ((data (with-current-buffer (url-retrieve-synchronously (format "%scomint" baseurl))
                         (goto-char (point-min))
                         (re-search-forward "\n\n")
                         (prog1
                             (buffer-substring-no-properties (point) (line-end-position))
                           (kill-buffer)))))
+            (cond ((string= (substring data 0 9) "<!DOCTYPE")
+                   (connect-is-with-url url))
                   ((string= (substring data 0 1) "")
                    (with-temp-buffer
                      (insert data)
                      (write-region (point-min) (point-max) file))
                    (setq *script-compilation-mode* :remote)
                    (fi:start-interface-via-file host "*common-lisp*" file)
                    (start-connect-is url))
                   (t
                    (message "There was an error connecting to the Intranet server")))))
          (t
           (message "Invalid url")))))
```
